// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prbilhapedmvltdqvnnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByYmlsaGFwZWRtdmx0ZHF2bm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU2NjksImV4cCI6MjA2NTU4MTY2OX0.nMIN2ADX_q6M7rW6IJ2_RVTtjh364eA0WGaLukC2dp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);